### ISSUE TITLE
Fix "Compatibility/Non-compliant license" issue in composer.json

### ISSUE THREAD

**Issue by williamdes** [wdes/account-manager#4]
Library `phpmyadmin/motranslator` is licensed under a non-compliant license: `GNU General Public License 2.0`

https://codeclimate.com/github/wdes/account-manager/composer.json#issue_5b0672fa90d34a0001000044

**Comment by williamdes** [comment]
@nijel Sorry for asking, can you help me with this issue ?

See: [fossa](https://github.com/wdes/account-manager#license)
![selection_021](https://user-images.githubusercontent.com/7784660/40318805-2fc80dce-5d26-11e8-823f-cbcb99d861da.jpg)

**Comment by nijel** [comment]
The motranslator code is based on https://launchpad.net/php-gettext/, that's where the license is coming from (GPL 2.0 or later). I don't see how I could help here.

**Comment by williamdes** [comment]
@nijel If I understand correctly, I need to add a mention/link to `motranslator` when I will create a release bundle.
Because the code of `motranslator` will be part of the files in the bundle.

I dont see why `fossa` and [gitlegal](https://github.com/kmewhort/git.legal-codeclimate) seem to say your license is incompatible with `MPL-2.0`.

If you say they are compatible, issue closed.

**Comment by ilikebits** [comment]
The MPL and the GPL-2 are NOT compatible. The GPL-2 expressly requires that any software which includes a GPL-2 library must itself be GPL-2.

**Comment by williamdes** [comment]
@ilikebits Ok, this is bad news.
Can you quote your source, I definitively need to know more for licenses...

**Comment by williamdes** [comment]
From what I found, big problems require big solutions.
Contamination from GPL will stop in https://github.com/wdes/account-manager/commit/bd66554a5383a1d515051577c078158683fb3e48 !
:biohazard: :skull_and_crossbones: 

See: https://softwareengineering.stackexchange.com/a/206795/287472

**Comment by williamdes** [comment]
Rewriting... at : https://github.com/wdes/php-i18n-l10n
